spring:
  datasource:
    driverClass: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost/main?serverTimezone=UTC
    username: root
    password: '!as112653'
    hikari:
      poolName: Hikari
      maximum-pool-size: 10
      max-lifetime: 240000
      connection-timeout: 5000

  jpa:
    hibernate:
      properties:
        hibernate:
          show_sql: true
      ddl-auto: validate

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      routing-key: alarm
    virtual-host: /alarm

server:
  servlet:
    encoding:
      force: true
      force-response: true
      charset: UTF-8
  port: 8080